
: THERE?C ( addr - flg )
 $80000 U>
 ;

REQUIRE NUMBER? _mak/lib/fpcnum.f

TRUE VALUE QUICK
: SL\ POSTPONE \ ; IMMEDIATE

[IFNDEF] FJB
 [DEFINED] GUI-CONSOLE
 [IF]  : FJB GUI-CONSOLE::FlushJetBuf ;
 [ELSE] : FJB ;
 [THEN]      
[THEN]      

 [UNDEFINED] ~DBG [IF] : ~DBG ; [THEN]

~DBG

\     0x174 CONSTANT QMCODE_SH
\     0x178 CONSTANT 'RESET_SH
     4 CONSTANT QMCODE_SH
     8 CONSTANT 'RESET_SH
QMCODE_SH 0x20000000 + CONSTANT QMCODE
'RESET_SH 0x20000000 + CONSTANT &RESET

\ 0x2000017C CONSTANT TDP
&RESET 4 + CONSTANT TDP

REQUIRE TC_?LIMIT _mak/lib/THERE/STAT.F

FLOAD _mak/lib/THERE/mthere.f
FLOAD _mak/lib/THERE/texec.4 
FLOAD _mak/lib/THERE/RECOM.F
: _, DROP 0 C, ;

#MAX
ENUM #F_WAIT
ENUM #ROM2RAM
ENUM #TO-G
ENUM #TO-R
ENUM #TO-B 
ENUM #INST
ENUM #?CR
\ ENUM #MASKA
ENUM #H.0
ENUM #.
ENUM #U.
ENUM #F.
ENUM #SETBASE
ENUM #TYPE
ENUM #SYN
ENUM #.R
ENUM #M>F
ENUM #OPEN
ENUM #CLOSE
ENUM #R-LINE
ENUM #R-FILE
ENUM #F-POS
ENUM #F-RPOS

ENUM #R-CHAR
ENUM #W-CHAR
ENUM #NEXTFILE
ENUM #FIRSTFILE
ENUM #GET-DIR-FILE-NAME
ENUM #GET-DIR-ATTR
ENUM #GET-DIR-SIZE

ENUM #TST
ENUM #RESET
ENUM #UTT
ENUM #JKEY
ENUM #GKEY?


  TO #MAX

