REQUIRE FIRSTFILE ~mak\lib\VDOS\FindFile.4
~mak\LIB\THERE\pfincl1.f 

: P_CLOSE
	DPF>
 ." C=" DUP .
 CLOSE-FILE >DPF ;

CREATE R-LINEBUF 0x104 ALLOT

: SPF>B:REM
  SPF>
 2DUP + 0!
 OVER W@ $20 OR S" b:" DROP W@ 2DUP H. H.  =
  IF  2 /STRING  THEN
 BEGIN OVER C@ '\' =
 WHILE 1 /STRING
 REPEAT ;

: P_OPEN
 CR ." P_OPEN=" 
	DPF> DUP H. FJB
 >R
 R-LINEBUF
 SPF>B:REM \ SPF> 2DUP + 0! 

 2DUP DUMP
\ ['] FIND-FULLNAME CATCH
\ IF	2DROP	RDROP 2 0
\ ELSE
CR    2DUP TYPE
	R> DUP 2 AND
	IF 2 XOR CREATE-FILE-SHARED
	ELSE
		>R ['] FIND-FULLNAME CATCH
		IF	2DROP	RDROP 0 2
		ELSE
			R> OPEN-FILE-SHARED
		THEN
	THEN	SWAP 
\ THEN
  DUP >DPF H.  DUP H.
 >DPF
;

: P_R-LINE
\ F7_ED
	DPF> >R
	R-LINEBUF
 DUP PF> 
 R>
 READ-LINE \ ABORT \ F7_ED
 2>R
	DUP >PF
." L=" 2DUP TYPE CR
 >SPF	R> R>
 >DPF >DPF
;


: P_R-FILE
\ F7_ED
CR ." RF="
	DPF> >R  
 DPF>  DUP ALLOCATE 
 IF RDROP 0 >DPF 0 >DPF -1  >DPF EXIT THEN
 TUCK SWAP
 R>       DUP .
 MREAD-FILE
 >R
	DUP >DPF
." F=" 2DUP H. H. CR
 >SPF
	R> >DPF
 FREE DROP
;

: P_R-CHAR
\ F7_ED
\ ." P_R-CHAR=" 
 0 >R
 RP@ 1 DPF> \ DUP H.
 MREAD-FILE 0= SWAP 1 = AND
	DUP >DPF
	IF  R> DUP EMIT >PF
	ELSE RDROP
	THEN
;

: P_W-CHAR
    H-STDOUT >R
    DPF> TO H-STDOUT
    PF> EMIT
    R> TO H-STDOUT
;

: P_F-RPOS
  DPF> \ fileid
  DPF> 
  DPF> \ fileid sw(ud)
  SWAP ROT REPOSITION-FILE >DPF
;

: P_F-POS
  DPF> \ fileid
  SWAP ROT REPOSITION-FILE ROT >DPF
 SWAP  >DPF >DPF
;

: P_NEXTFILE
\ CR ." NEXTFILE="
\ 0 \
 NEXTFILE
\ DUP . 
>PF ;

CREATE DIR-LINEBUF  0x104 ALLOT

: P_FIRSTFILE
CR ." FIRSTFILE="
	DIR-LINEBUF
 SPF> 2DUP + 0!
\ OVER W@  S" b:" DROP W@ $20 OR 2DUP H. H.  =
\  IF  2 /STRING  THEN
\ BEGIN OVER C@ '\' =
\ WHILE 1 /STRING
\ REPEAT
 2DUP TYPE
\ 2DROP 0 \ 
 FIRSTFILE
 DUP . >PF \ KEY DROP
 ;

: P_FIRSTFILE_B
CR ." FIRSTFILE="
	DIR-LINEBUF
 SPF>B:REM
 2DUP TYPE
\ 2DROP 0 \ 
 FIRSTFILE
 DUP . >PF \ KEY DROP
 ;

: P_GET-DIR-FILE-NAME
\ CR ." GET-DIR-FILE-NAME"
\ S" TEST.TST" \ 
   GET-DIR-FILE-NAME
 >$PF ;

: P_GET-DIR-ATTR
    GET-DIR-ATTR >PF ;

: P_GET-DIR-SIZE
    GET-DIR-SIZE >DPF ;
